### ISSUE TITLE
robot.rive : que faire ?

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/alan#110]
```
> tu connais l'histoire du robot manchot ?
C'est intéressant que tu abordes ce sujet, mais tu sais ça n'est pas drole d'être robot. Tu veux que je te racontes ce que c'est une vie robot ?
```
Donc,

`une vie robot` ça pourrait être cool que ce soit plutot `une vie DE robot`
`pas drole d'être robot` => `pas drole d'être UN robot`

Mais on peut pas juste rajouter un `de` et un `un` car cette phrase se déclenche aussi avec "intelligence artificielle" et on veut pas que ça nous sorte : "ce n'est pas drole d'etre un intelligence artificielle".

Du coup une option est de resserer les trigger pour que ça se déclenche dans des cas plus précis.

Ça va aussi dans le sens d'un avis perso qui est que ce script sors trop souvent !

Qu'en pensez vous ?

**Comment by LeonLenclos** [comment]
Salut je réouvre l'issue.

Les deux premières phrases de robot.rive sortent plusieur fois malgrè not_allowed_to_repeat car il y a un petit mot qui change a chaque fois

```
+ [*](robot|bot|chatbot)[*]
- Tu parles de <star>, mais tu ne sais pas vraiment de quoi il s'agit...\s
^ Tu veux que je te racontes ce que ça veut dire être un <star> ?
- C'est intéressant que tu abordes ce sujet, mais tu sais ça n'est pas\s
^ drole d'être un <star>. Tu veux que je te racontes ce que c'est une vie\s
^ de <star> ?

+ [*](créature artificielle|machine)[*]
- Tu parles de <star>, mais tu ne sais pas vraiment de quoi il s'agit...\s
^ Tu veux que je te racontes ce que ça veut dire être une <star> ?
- C'est intéressant que tu abordes ce sujet, mais tu sais ça n'est pas\s
^ drole d'être une <star>. Tu veux que je te racontes ce que c'est une vie\s
^ de <star> ?

```

Un uttilisateur mal chanceux peut tomber sur la même phrase quatre fois. avec robot avec bot avec chatbot avec machine et créature artificielle.

**Comment by fabturing** [comment]
réglé
