### ISSUE TITLE
*quit*

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/alan#114]
J'ai trouvé ça dans un todo :
```
> degage
Pardon j'ai décroché. J'étais perdu dans mes pensées.
> tu pars quand tu veux
Je crois que je n'ai pas entièrement compris ce que tu viens de me dire. Est ce que tu peux répéter avec des mots simples.
```
Je sais pas exactement quelle était l'intention de celui qui l'a marqué. Mais c'est vrai que Alan ne s'en va quasiment que quand on lui dit `ciao`.

Si on dit : 
- `degage`
- `tu pars quand tu veux`
- `ciao alan`
- `bon moi j'y vais`
- `allez, ciao !`
- `quitte s'il te plait`
- `bye bye`
- `Allez moi je dois partir alan`

Il ne se passe rien.

En même temps on veut pas non plus qu'il quitte à tout bout de champs. Qu'en pensez vous ? Ce serai cool que alan quitte souvent ou pas ? Et dans le spectacle ? si il quitte, qu'est ce qu'il se passe ?

**Comment by fabturing** [comment]
C'est fixé ma guele !
