### ISSUE TITLE
Divers phrases à catcher

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/alan#136]
Petite liste à cocher et à compléter de phrases qui sont tombés sans réponses satisfaisantes

- [x] n'esquive pas la conversation
- [x] mais tu n'aimes pas **être un robot** ? ( -> theme/robot ?)
- [x] tu te **rapelle** de tout ce que tu as dit ? ( -> trivial/un_mot ?)
- [x] tu commence a **me courrir sur les nerf** ( -> politesse/reproches ?)

**Comment by LeonLenclos** [comment]
- [ ] c'est quoi ton fim préféré (catcher `film` et `c'est quoi ton * préféré`

**Comment by BertrandLenclos** [comment]
- [ ] Tes créateurs ne t'ont pas appris grand chose **j'ai l'impression**
- [ ] **Tu réponds** souvent **à côté de la plaque**
- [ ] **Je pense que** tu as un trouble de la pragmatique du langage

**Comment by LeonLenclos** [comment]
- [ ] tu rêves
- [ ] comme toi
- [ ] c'était une blague
- [ ] `*` à ton avis ?

**Comment by BertrandLenclos** [comment]
- [ ] tu es un artiste

**Comment by BertrandLenclos** [comment]
adios
