### ISSUE TITLE
collaborateurs

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#157]
faire en sorte qu'Alan connaisse tous les collaborateurs du spectacle

Cie Nokill
- [ ] Pascale Maison
- [ ] Amparo Gallur
- [ ] Francis Lopez
- [ ] Virginie Talou

Irit
- [ ] Michel Daydé
- [ ] Tim van de Cruys
- [ ] Philippe Muller
- [ ] Isabelle Ferrané
- [ ] Thomas Pellegrini
- [ ] Véronique Debats
- [ ] Michael Vo
- [ ] Claire Mevolhon

- [ ] Claire

**Comment by LeonLenclos** [comment]
+ quai des savoirs et tous les lieux ou on va en résidence

**Comment by BertrandLenclos** [comment]
done
