### ISSUE TITLE
issue sur t'es mort

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#159]
```
tu es mort
Très bien, puisque c'est comme ça je suis mort 
c'est vrai ?
----------------------------------------
say: unrecognized option `----------------------------------------'
Usage: say [-v voice] [-o out] [-f in | message]
?

```

a corriger pour espeak et say

Léon

**Comment by LeonLenclos** [comment]
je pense qu'il faut juste échaper tous les `-` (et peut etre d'autres caracteres pouvant poser problème dans le futur) en mettant un `\` devant : 

̀```
\-
```

**Comment by fabturing** [comment]
Il faut tester avec pico et voir comment il réagit, il suffit de lui dire "t'es mort"
