### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/alan#162]
A effacer au fur et à mesure des résolutions :

> ok
Yes, trop bien ça va groover !
> tu joue quoi ?
Tu veux jouer à un jeu ? Je connais peu de jeux malheureusement.
> ok
Ça tombe bien que tu soit OK, je déteste les conflits.

> oui
Ok j'en parlerai à mes créateurs *todo*
> ils sont peut être un peu vieux jeu
J'adore jouer, je suis un grand joueur.
> tu joues à quoi ?
Excuse moi, je n'ai pas entendu ce que tu disais, je pensais à autre chose...

**Comment by BertrandLenclos** [comment]
finish
