### ISSUE TITLE
divers à catcher

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#170]
- [x] tu as des projets

**Comment by LeonLenclos** [comment]
- [ ] tu veux parler de quoi ?
- [ ] de quoi tu veux parler ?
- [ ] tu me racontes un truc ?

**Comment by LeonLenclos** [comment]
Vu dans une conversation au quai des savoirs.
- [ ] Les mots "rigoler", "pleurer", et leurs conjugaisons les plus courantes
- [ ] tu casses les couilles
- [ ] tu as raison (tu as tout à fait raison)
- [ ] fais-tu ... ? / tu fais ... ? (e.g. fais-tu du sport ?)
