### ISSUE TITLE
Proposition réorganisation des settings et des rives

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/alan#186]
# Rive

L'idée c'est de créer 2 nouveaux dossiers dans rive/

### audio

Pour tout ce qui concerne la voix d'alan ou des sons qu'il peut produire

### online

Pour tout ce qui est exclusivement lié à la présence d'alan sur internet

(peu de choses pour l'instant mais surement utile plus tard)

### spectacle (existe déjà)

Pour tout ce qui est utilse qu'en spectacle ou qui n'a de sens que si on est  physiquement en présence de alan 

# Settings

L'idée est d'avoir 4 fichiers settings selon les utilisations

### default

Utile pour bosser sur alan.

- Commande à executer : `alan.py` ou `alan.py -s default`
- Interface : Dans le terminal avec stt
- Logic : Tout les logics adapter

### spectacle

À lancer en spectacle.

- Commande à executer : `server.py -s spectacle` puis visiter `/labo.html`
- Interface : interface web avec stt
- Logic : Tout les logics adapter sauf `rive/online/*.rive`

### local

À lancer en expo.

- Commande à executer : `server.py -s local` puis visiter `/index.html`
- Interface : interface web avec stt
- Logic : Tout les logics adapter sauf `rive/online/*.rive` et `rive/spectacle/*.rive`

### internet

À lancer sur le server pour mise en ligne.

- Commande à executer : `server.py -s internet` puis visiter `/index.html`
- Interface : interface web sans stt
- Logic : Tout les logics adapter sauf `rive/audio/*.rive` et `rive/spectacle/*.rive`

**Comment by LeonLenclos** [comment]
@fabturing J'attend que tu me confirme que tu n'as pas chez toi du travil non pushé qui entretrait en conflit avec ça. Si c'est bon, et que tu n'as pas de meilleure idée, je commenc à mettre ça en place.

**Comment by fabturing** [comment]
Feu vert amigo

**Comment by fabturing** [comment]
stt c'est bien la synthèse vocale non ? (du coup c'est tts (text to speach) ou je dis n'importe quoi?)

**Comment by LeonLenclos** [comment]
tu dis pas nimporte quoi c'est moi qui dit nimporte quoi. c'est bien tts et pas stt

**Comment by LeonLenclos** [comment]
corrigé dans le settings/README.md
