### ISSUE TITLE
aspell

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/alan#188]
Il faudrait enlever aspell de requierment.txt.

Le fichier requierment.txt doit contenir une liste de packages python pour être installé via pip ([doc officielle](https://pip.readthedocs.io/en/1.1/requirements.html))

Et apparament aspell n'est pas un package python (??)

À la place il faudrait détailler l'installation de aspell dans le readme genre ici : https://github.com/LeonLenclos/alan/tree/develop#4-installer-un-dictionnaire

**Comment by fabturing** [comment]
Fait, tu peux fermer mais jette quand même un oeuil au readme: https://github.com/LeonLenclos/alan/tree/develop#4-installer-un-dictionnaire

**Comment by LeonLenclos** [comment]
:+1:
