### ISSUE TITLE
Idées de scénario rivescript à faire

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#193]
- [ ] en partant d'un catch all, Alan essaye d'extirper le n° de CB du user pour s'acheter un jeu (ou une extension) sur internet.
- [x] Alan réagit à un user qui essaye de lui extirper son n° de CB (vu ans les conv)

**Comment by LeonLenclos** [comment]
C'est fait il manque plus qu'à trouver un bon catch all qui contient la phrase "ton numéro de carte bleue"

Les previous dans decales.rive recupereront la reponse

(peut aussi etre lancé avec une chance sur deux par "argent" (dans un_mot))

**Comment by LeonLenclos** [comment]
Je ferme l'issue, il y  pas de catch all mais plusieurs sujets qui renvoient vers ça.
