### ISSUE TITLE
aide_rivescript.md dans la doc

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#195]
J'ai commencé [un fichier d'aide à la programmation du rivescript d'Alan](https://github.com/LeonLenclos/alan/blob/develop/doc/aide_rivescript.md) à partir de mon vécu de ces 15 dernier jours. 
A corriger/compléter.
Par ailleurs j'ai fini (c'est jamais fini....) ma passe sur Alan en vue de la mise en ligne.
C' est a tester sur la branche develop.
Domage que j'ai capté trop tard l'intérêt de la wildcard _ dans les mots...
Ça sera pour plus tard...

**Comment by LeonLenclos** [comment]
vu.

Dans l'idée de netoyer un peu les isssue est-ce que @fabturing  tu pourrai fermer celle-ci dès que tu en as pris connaissance ?

**Comment by fabturing** [comment]
Vu, bravo pour le boulot Bebert
