### ISSUE TITLE
ajustements avant mise en ligne

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#198]
Quelques propositions de modifs de dernière minute 

- [x] Est ce qu'il ne faudrait pas adopter un débit progressif comme en TTS ? en tout cas un peu moins rapide

- [x] il y a plein de conversations stockées et vides type 
```
chut
> ... *chut*
```

- [x] Alan quitte sans dire la dernière phrase, dans la conv si dessous je n'ai pas vu la dernière phrase ` - fait de beaux rêves`

```
by by
> Ça me laisse sans voix ce que tu viens de me dire
je te quittes
> J'ai peur de ne pas comprendre. Qu'est ce que tu veux dire exactement ?
je vais me coucher
> Fais de beaux rêves ! *quit*
```

- [x] Sur la tablette, on ne voit pas le rectangle saisi de texte à l'arrivée sur la page. Si on ne sait pas que c'est en dessous du rectangle conversation, on est perdu... peut-être adapter la taille du rectangle conv a l'écran du user ???

- [x] est ce qu'on ne devrait pas fermer des conversation après un temps d'inactivité ? ou de déconnexion du user ? Sinon on va se retrouver avec des kilos de conversations ouvertes non ?

**Comment by LeonLenclos** [comment]
>  Est ce qu'il ne faudrait pas adopter un débit progressif comme en TTS ? en tout cas un peu moins rapide

Alors en effet je viens d'enlever (pour le mode muet) cette fonctionnalité qui était **côté serveur** dans le but de soulager ce dernier. La prochaine étape serait de la passer **côté client**. Mais ça demande de revoir un peu le fonctionnement du client.

>  il y a plein de conversations stockées et vides type

Oui, la solution sera simplement d'enlever le chut en mode muet (car utile que pour corriger un bug de synthèse vocale)

(a verifier aussi si en TTS le chut est encore utile maintenant qu'il y a les toussotements ??)

>  Alan quitte sans dire la dernière phrase, dans la conv si dessous je n'ai pas vu la dernière phrase - fait de beaux rêves

Oups, c'est un bug dû aufait que Alan devait quitter directement apres sa derniere réplique (issue #187 ).

Je pensait avoir régler ce problème, manifestement non. C'est peut etre le plus urgent !


>  Sur la tablette, on ne voit pas le rectangle saisi de texte à l'arrivée sur la page. Si on ne sait pas que c'est en dessous du rectangle conversation, on est perdu... peut-être adapter la taille du rectangle conv a l'écran du user ???

cf. isue #184 " *Voir comment se comporte l'interface sur d'autres navigateurs que firefox*"  -> Je ne m'en suis pas encore occupé !

À voir si j'arrive à regler le pb sans tablette sous les yeux.


>  est ce qu'on ne devrait pas fermer des conversation après un temps d'inactivité ? ou de déconnexion du user ? Sinon on va se retrouver avec des kilos de conversations ouvertes non ? 

Déjà réglé (cf. issue #176 [ce commentaire](https://github.com/LeonLenclos/alan/issues/176#issuecomment-443050119)) 

actuellement `CONVERSATION_LIFETIME` est réglé sur **10h**

**Comment by LeonLenclos** [comment]
>  il y a plein de conversations stockées et vides type

Pour ça j'ajoute une liste de conversation filtrée (que les conversation qui font > 5 lignes)

**Comment by LeonLenclos** [comment]
>  Est ce qu'il ne faudrait pas adopter un débit progressif comme en TTS ? en tout cas un peu moins rapide

@BertrandLenclos  Je veux bien plus de details sur ce que tu voudrai

> Sur la tablette, on ne voit pas le rectangle saisi de texte à l'arrivée sur la page. Si on ne sait pas que c'est en dessous du rectangle conversation, on est perdu... peut-être adapter la taille du rectangle conv a l'écran du user ???

@BertrandLenclos Je veux bien une capture d'écran
