### ISSUE TITLE
bug affichage firefox

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/alan#200]

**Comment by fabturing** [comment]
Petit beug sur firefox ESR 68.7.0 au niveau de l'affichage :
Parfois  le texte entré par l'utilisateur dans la zone de frappe met un peu de temps à s'afficher dans la conversation au dessus. C'est pas très grave mais cela à entrainé quelque-chose d'étrange dans l'affichage que je vous décrit ci-dessous, en précisant que tout cela s'est passé très vite mais que je suis assez sur de l'ordre des évènements:
-Alan m'a posé une question
-J'ai tapé rapidement fip dans la zone de frappe puis j'ai appuyé sur enter.
- là 'fip' a (logiquement) disparue de la zone de frappe, mais il n'avait pas eu le temps d'apparaitre dans la conversation
- Ayant l'impression que ma réponse était perdue car ne la voyant nulle part je retape fip puis enter dans la zone de frappe
- Finalement mon premier fip c'est affiché dans la conversation, ainsi que la réponse d'alan, le deuxième fip est cependant resté dans la zone de frappe
- J'ai fait espace et le fip de la zone de frappe a disparu.

De plus:
-On peut spamer alan en appuyant sur une lettre puis sur enter un grand nombre de fois, alan est alors en retard sur la conversation et traite toutes les réponses mais pas toujours dans leur ordre d'arrivée !

Je pense qu'il faudrait que quand l'utilisateur appuie sur enter, en même temps que le texte entré disparait, la zone de frappe soit inactive et grisée (comme quand Alan a quitté) et qu'elle redevienne active une fois que toute la réponse d'Alan s'est affichée.

**Comment by LeonLenclos** [comment]
Ok yes, c'est pas specifique à ton navigateur. C'est pareil pour tout le monde.

À fixer.
