### ISSUE TITLE
Todo internet /dev

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#201]
Est ce qu'on pourrait les ranger dans l'ordre inverse. Les plus récents en premier.

**Comment by LeonLenclos** [comment]
hm... Je sais pas.
Ça me semble un peu tordu, quand on ajoute des lignes à un fichier avec un programme, l'usage est plutôt de les ajouter à la fin.

Mais je me disais peut etre un moyen de vider le fichier todo avec un bouton sur le dev panel ?? ça t'irai comme solution ?

**Comment by BertrandLenclos** [comment]
Ok pour le bouton effacement

**Comment by fabturing** [comment]
yes

**Comment by LeonLenclos** [comment]
ok, pour l'instant on va tester la commande [`cleartodo`](https://github.com/LeonLenclos/alan/commit/edf0da3c0560a9fd327ada6a82cf8137d198df4f)
