### ISSUE TITLE
todo à régler en Python (pas de solution. rive possible)

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#208]
- [x] certains user utilise le "?" pour dire qu'il ne comprennent pas. (conv 224 par exemple).
ca serait super d'aménager un réponse en python car "?" est interdit dans les triggers .rive .

- [ ] Pareil pour les smiley (conv 262)

**Comment by LeonLenclos** [comment]
Alors les smiley j'ai créé un préprocesseur qui remplacerait les smiley par des mots. Mais en y reflechissant j'ai peur que ça ai des consequences pas cool.

Genre,
    > Tu connais jul ? :)
    > Non je ne connais pas jul emoticon_happy

Donc pour l'instant c'est dans la branche "emoticon" et on verra plus tard.
