### ISSUE TITLE
Confiance oui/non

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/alan#210]
sur les input "oui" et "non" (assez fréquents) Alan déclanchais politesse/divers.rive et maintenant il declanche trivial/un_mot_array.rive

Je pense que l'inverse serait mieux (un_mot_array est plus hasardeux sur oui/non donc ce serait bien qu'il n'arrive qu'en dernier recours) donc je pensais monter la confiance de politesse/divers mais vu que tout ca est un equilibre fragile je prefere demander avant

**Comment by BertrandLenclos** [comment]
Je pense que ça se tente.

au dessus de 0,47 : 0,5 ?

Tu le fais ?

**Comment by LeonLenclos** [comment]
Ok, je met politesse/divers  à 0.5 (au lieu de 0.35)
