### ISSUE TITLE
Un_mot_array et oui/non

### ISSUE THREAD

**Issue by fabturing** [LeonLenclos/alan#216]
J'ai remarqué que de temps en temps Alan répondait juste : "Pas.". En fait c'est du à cette partie de un_mot_array:
` + [*] (@no) [*]`
`- {sentence}(@no){/sentence}.`
Puisque pas est dans l'array `@no`. Je pense que ce dont il faut se méfier dans les array c'est le fait que certains arrays ont étés pensés pour détecter des choses et donc sont très ouverts concernant ce qui doit appartenir à l'array. Je trouve que les array de détection ne sont pas toujours adaptés à être utilisés dans les réponses d'Alan (on avais déja des choses un peu étranges quand alan disait par exemple "je suis en mode admirablement" en cherchant au hasard dans le tableau `@positive`)

Pour un_mot_array qui se déclenche très souvent sur `@yes` et `@no` je me dis que ce serait peut être mieux de faire deux ou trois réponses fixes, ça l'empécherait de se déclencher trop souvent et éviterai d'avoir à enlever des mots comme pas qui sont bien quand on se sert de `@no` en mode détection.
Je m'en occupe dès que j'ai votre accord.

**Comment by LeonLenclos** [comment]
D'accord pour dire que les réponses de un_mot_array sur oui/non sont problematique. Surtout que c'est souvent déclanché.

La solution peut être, comme tu propose de garder le même trigger mais de plus cadrer les réponses. (si tu t'en occupe attention à ne pas faire de doublon avec les oui/non de politesse/divers.

---

De manière plus général les arrays sont pour moi un outil super puissant mais à double tranchant.

Pour leur utilisation **dans les déclancheurs**, c'est vraiment super pratique dans plein de situation. Je pense notament aux bouts de codes qu'on se retrouve à écrire super souvent et qu'on peut automatiser (les fameux `(es tu|tu es|est ce que tu es) content de me voir` qu'on peut remplacer par `(@areyou) content de me voir`). Et c'est aussi très pratique pour élargir le vocabulaire `(@areyou) (@happy) de me voir`.

Mais ça à le deffaut qu'on est pas toujours conscient de tout ce qu'il y a dans l'array quand on l'utilise. Et que ça peut être très large.

_un_mot_array_ est un super adapter car il est très efficace en terme de rapport _effort de redaction / nombre de cas couverts_. Mais dans les faits je lui fait presque pas plus confiance qu'à _catchall_ 

L'autre soucis est sur leur utilisation **dans les réponses**. Il y a le problème des fois ou on avait pas anticipé que ça sonne mal ("je suis en mode admirablement"). Mais là où c'est le plus problématique pour moi c'est quand il y a un array dans une longue réponse. En créant une petite variation ça contourne l'interdiction de se répéter. Mais pour l'interlocuteur c'est vraiment senti comme une répétition.  J'ai pas d'exemple sous la main mais des trucs qui ressemblerai à ça:
```

> Je suis très content que tu me parles de robot, sais-tu que moi-même je suis un robot ?
(...)
> Je suis très heureux que tu me parles de robot, sais-tu que moi-même je suis un robot  ?
```
Franchement c'est bof..

Donc concrettement je pense qu'il faut continuer à massivement utiliser les array mais à condition de mieux les maitriser. Peut être les enlever des réponses longues.

Et garder en tête que notre but n'est pas d'éviter les catchall à tout prix. Mais d'éviter les catchall à condition d'avoir mieux à dire.

**Comment by BertrandLenclos** [comment]
En ce qui concerne le problème exposé par Fabien, je pense que la bonne solution c'est de faire des array réponse dans lesquels on élimine les réponses qui ne sonnent pas bien. J'ai un peu commencé, mais il faudrait que ce soit systématique et c'est un gros boulot...

En ce qui concerne la remarque de Léon j'ai surtout remarqué cela dans les conv avec le scénario suivant : 
```
+ [*] (@intelligent_synonymous) [*]{weight=2}
- C'est en devenant vraiment très (@intelligent_synonymous) que je réussirais\s
^ peut-être un jour le test de Turing.
```
En effet ce type de réponse longue est inadaptée à "un mot array". A changer donc.

Sinon je voulais vous parler d'un problème avec les attributs, mais j'ouvre un issue pour cela.

**Comment by LeonLenclos** [comment]
Bon donc si on se concentre juste sur le soucis innitial de cet issue c'est donc ce bout de code dans un_mot_array :+1: 

> 
> + [*] (@yes) [*]
> - {sentence}(@yes){/sentence}.
> 
> + [*] (@no) [*]
> - {sentence}(@no){/sentence}.
> 

Il a deux problèmes : 

### Il peut se déclenche à des moments bizarres 
e.g.  "je mange **si** j'ai faim"
La solution peut être :
- le restreindre à `(@yes)` au lieu de `[*](@yes)[*]`


### Il produit des réponses bizarre
e.g. "Pas"

2 Solutions : 
- avoir un grand nombre de réponses possibles en partant de l'array `@yes` en faisant un tri
- n'avoir que deux ou trois réponses et l'autoriser à se repeter (en creant un rive exprès pour toutes les miniphrases que c'est pas choquant si elles se repettent)

**Comment by BertrandLenclos** [comment]
ok pour le `(@yes)` au lieu de `[*](@yes)[*]`
pour le reste je vote pour un array yesresponse trié (utilisable ailleurs). et un rive spécial avec autorisation de se répéter.

**Comment by BertrandLenclos** [comment]
Bon je crois qu'on a bien avancé sur cette issue. 
J'ai fait ce qui est noté ci-dessus et léon a modifié les "not allowed to repeat" pour les limiter au phrases de plus de trois mots. Les problèmes semblent réglés.
Si Fabien est daccord on close.

**Comment by BertrandLenclos** [comment]
Concernant les dangers de la modif `(@yes) au lieu de [*](@yes)[*]` 
Les problèmes sont arrivés plus tôt que prévus...
voir conv 460 :
``` 
> Heureux de te rencontrer Sabrina. Comment ça va ?
bien et toi?
> Et bien moi j'ai pas trop la pêche en ce moment. Un peu pas trop. Mais ça vas me remonter le moral cette discussion Sabrina.
oui moi aussi
> Je ne sais pas du tout quoi te répondre. Tu as trouvé une faille dans mon programme. À ton avis, est ce qu'il faut que j'en parle à mes créateurs ?
c'est certain
``` 
Franchement dommage....

**Comment by LeonLenclos** [comment]
je croyais que _moi aussi_ déclenchais un truc du genre _alors on est deux_...

Mais je dois confondre.

Sinon pour ce problème, peut être `[_][_](@yes)[_][_]` ? Je sais pas...

Ou retour à ` [*](@yes)[*]` mais  `@yes` sans "si" et `@no` "pas" ?

**Comment by BertrandLenclos** [comment]
ok pour une des deux solutions ci-dessus.
peut-être aussi rajouter une option devant moi aussi.
Pour l'instant c'est : 
```
+ (moi aussi|moi pareil)[*]
- Alors on est deux !
- Ça nous fait au moins un point commun.
```

**Comment by LeonLenclos** [comment]
>  peut-être aussi rajouter une option devant moi aussi.

Je dirais que ça dépend de la confiance de son adapter... Si c'est un adapter de confiance ça peut etre une mauvaise idée de trop l'assouplir.

**Comment by BertrandLenclos** [comment]
formel = 0.43 sauf erreur c'est la plus faible avant catch all

**Comment by fabturing** [comment]
Du coup je suis ok pour tout:
- l'option devant moi aussi pour un formel ça me parait bien et pas trop dangereux
- POur le yes, [_][_](@yes)[_][_] me parait un bon compromis
