### ISSUE TITLE
Todo or not todo

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#218]
Comment savoir si quelqu'un s'est occupé des todo ? 

Perso j'adopte la technique de signaler ce que j'ai fait dans Alan avec un todo. Mais j'ai l'impression que je suis le seul ?

Pour info j'en suis à la 392, mais comme Alan est buggé...je ne peux pas le signaler.

**Comment by LeonLenclos** [comment]
_cleartodo_ ?
