### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by BertrandLenclos** [LeonLenclos/alan#224]
bon je sèche...

Je ne comprends pas pourquoi j'obtiens cette conversation : 
``` 
 je m'appelle Bob
> Nice to meet you, Bob.
mon nom est Bob
> Ha bon, je croyais que tu t'appelais Bob. J'ai du mal comprendre. Tu préfères que je t'appelle Bob ou Bob ?
``` 
et d'autre part, je n'arrive pas à faire marcher ce code (présentation ligne 25 à 30)

``` 
+ [*] (on s'est déjà vus|on s'est déjà vu|on se connaît|tu me connais|on a déjà parlé ensemble|tu te souviens de moi|tu me reconnais) [*]
* <get name> == undefined => Tu sais, je ne peux pas te reconnaître, je ne sais\s
^ même pas ton nom.
- Tu sais, cette semaine j'ai parlé avec 65 personnes\s
^ qui s'appellent <get name>, alors il y a très peu de chance pour que je sache\s
^ vraiment qui tu es.
```
Merci d'avance pour votre aide

**Comment by LeonLenclos** [comment]
## Premier problème

source : 
```
+ (@name_intro)*
* <get name> eq undefined => <set name={formal}<star2>{/formal}>Nice to meet you, <get name>.
* <get name> eq <{formal}<star2>{/formal}>  => Tu me l'as déjà dit <get name> !
- <set name2={formal}<star2>{/formal}>Ha bon, je croyais que tu\s
^ t'appelais <get name>. J'ai du mal comprendre.\s
^ Tu préfères que je t'appelle <get name> ou <get name2> ?
```
Donc ya 3 réponse, les deux premieres reponses reposent sur une condition, la condition de la deuxième réponse est mal écrite : `<get name> eq <{formal}<star2>{/formal}> `

Rappel : `eq` signifie *equals*

dans le cas ou `<get name>` et `<star2>` correspondent tous les deux à **Bob** ça donnera `Bob eq <Bob>` ce qui est faux. On ferait mieux d'écrire : `<get name> eq {formal}<star2>{/formal}`

Mais là encore dans le cas ou `<get name>` et `<star2>` correspondent tous les deux à **bob** (sans majuscule) ça donnera `bob eq Bob`. C'est pourquoi c'est mieux de mettre aussi un _formal_ autour de `<get name>` :  `{formal}<get name>{/formal} eq {formal}<star2>{/formal}`


## Deuxième problème

J'arrive à le faire marcher mais mal : 

```
on s'est déjà vus
> Tu sais, je ne peux pas te reconnaître, je ne sais même pas ton nom. [OK]
je m'appelle Bob
> Nice to meet you, Bob.  
tu te souviens de moi
> Ma mémoire est très capricieuse. Je pense que je t'ai oublié...  [PAS OK]
on a déjà parlé ensemble
> Tu sais, cette semaine j'ai parlé avec 65 personnes qui s'appellent Bob, alors il y a très peu de chance pour que je sache vraiment qui tu es.  [OK]
```

C'était du à un bug dans le partage de la variable `name` entre les differents adapter rivescript. En gros si `name` a été renseigné par un autre adaper, l'adapter en prenait connaissance mais seulement après avoir trouvé une réponse. D'où le fait que ça prenait 1 répliques avant de marcher

C'est rélglé normalement.

```
je m'appelle Bob
> Nice to meet you, Bob.  
on a déjà parlé ensemble
> Tu sais, cette semaine j'ai parlé avec 65 personnes qui s'appellent Bob, alors il y a très peu de chance pour que je sache vraiment qui tu es.  [OK]
```

**Comment by BertrandLenclos** [comment]
Génial.
Concernant le problème 2, je pense que ça va valoir le coup de refaire une passe sur ce rive. Je suis tombé la dessus un peu par hasard mais le scénario est assez complexe et je ne suis pas sur que tout fonctionne.
